<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <p>
      This morning, I managed to get out of the house, in pursuit of nothing but to avoid surrendering to my daily urge
      of going to sleep, today I wanted to break the cycle, actually I have wanted to break the cycle of laziness for
      far too many days, and so far I have succeeded to do it.
    </p>
    <p>
      It is only 11:06 and I feel tired, but that’s something I expect, so it is not surprising. So far I’ve had 3
      espressos, yet I can feel my body telling me to get some sleep but I am not going to give up at least not today
      and certainly not tomorrow or the day after.
    </p>
    <p>
      I have wasted so many precious days on the illusion that I am going to make it in this life automatically, just
      because I am destined to, just because that’s what I have always been told in my life, that somehow just because I
      am me, I am going to daydream my way into life and end up in a mansion on a tropical island.
    </p>
    <p>
      But now it is time for the truth, for my confession, I have to work just as hard as anyone else, or even much
      harder, I will not end up where I want to just because there is something special about me, apart from some
      technical fluency that I have acquired as a child on nothing but the fuel of passion of crafting things, I have
      nothing in this life, not even a passport that can get me far, or some basic human rights that others might have,
      it is not a complaint, but stating facts as they are, and considering all this the illusion of getting anywhere
      near the level of success that I want out of the blue, becomes nothing but a more horrendous joke, and it is time
      for me to confess to that.
    </p>
    <p>
      I am a minority of another minority, undesired by the majority of each group that I belong to, and that is just
      fine by me as long as I can stand my truth which is the only thing that I care about at this point.
    </p>
    <aside>💡 The truth will set you free - a wise man said.</aside>

    <p>
      So I see no reason to not further my level of commitment to the truth that it currently is, which is the last and
      perhaps the hardest step for me, and that is to stop lying to myself.
    </p>
    <p>In my estimate, it is much harder to be truthful to oneself than it is to the outside world.</p>
    <p>
      You can always wear a mask of virtue and appear truthful to the public, but what matters is the inside and not
      being rotten inside by all the lies you tell yourself.
    </p>
    <p>And to start my journey in pursuit of inner truth, I have to confess, clear the slate and ‘set myself free.</p>
    <p>
      Life is hard, people work hard, or at least they show up, forget about the one-in-a-million event, where an
      asteroid of gold hits someone’s backyard that is just that: Pure luck.
    </p>
    <p>Having royal blood or a good neighborhood right outside of the womb is just that - luck.</p>
    <p>
      If you are anything like me, chances are you have none of those things you have to build who you are. One of the
      perks of being born with nothing - no pre-destined career that you must go into to meet your ancestors&#39;
      exceptions of you. You get to build your own character, and god only knows how fun it can be.
    </p>
    <p>
      So back to my story, today I spent a few hours walking the street which I usually walk during the night time, you
      know just to eat dinner and get back to rotting in my bed. I walked the street with a sense of wonder, with my
      eyes wide open, and I noticed how hard people work at that point I felt nothing but shame. I saw an old man
      carrying two big baskets of goods on his back, that was maybe 8:30, and he was there, on the street so that he
      could provide for himself and maybe a family. Chances are he has been doing that for years, maybe as long as he
      can now recall, not necessarily selling stuff on the street, but more fundamentally being out there.
    </p>
    <p>
      As I wandered the streets I kept seeing familiar faces, faces I had seen the nights before. And that is when I
      realized what had become the beginning of the day all those nights, was the end of a very hard-working day of most
      of the familiar faces I had seen. They were always there, present at the last minutes of their shifts, serving
      their last customer - usually me - and how dare I demand any level of achievement when I know I am not working as
      hard as any of these people. Chances are these wondering hard-working people are struggling with their life, and
      still they keep pushing it, they are not wasting days of their life rotting in bed because they are “depressed”,
      they show up when I don’t. And again I have to emphasize how dare I expect anything out of life if I know I am not
      working anywhere near as hard as these people?
    </p>
    <p>
      When was the last time that I started working and finished 10 hours later and got surprised by how the time went
      by? - I do not know.
    </p>
    <p>
      But things should change, I am an ambitious person, and laziness will only turn an ambitious man into the most
      miserable version of himself.
    </p>
    <p>
      For way too long I have been hiding behind empty words that may not even exist outside of their form of serving as
      meaningless excuses, labeling myself as depressed or having low stamina, and every other form of self-fulfilling
      prophecies.
    </p>
    <p>
      States of being that may not exist on you if you had never heard of the word that describes them, man-made words
      serving the evil purpose of giving up on yourself and still feeling good about your lack of achievements in this
      life, escape boas for those scared of the sand!
    </p>
    <p>
      Even if there is not a mountain to climb, my life has a goal, to not feel regret when days go by, and to not waste
      a second of my life.
    </p>
    <p>
      I have a duty, to myself and to the world, and that is to fulfill my full potential, to be who I could be if I had
      not made stupid decisions.
    </p>
    <p>
      So this was my confession, and I feel much better, my mind feels freedom it had not felt for a long time, now that
      the slate is clean again, now that I have once again aligned the man inside with the outside persona that I show,
      I once again know who I am.
    </p>
    <p>
      At least I know I have a chance of being true to myself once again in my life, and I am going to make a promise to
      myself along with this confession, I am going to use all of my time, sleep well, and on time and take care of my
      body as well as my mind.
    </p>
    <p>2022/12/10 12:20 Istanbul.</p>
  </article>
</Post>
